spring:
  datasource:
    url: jdbc:postgresql://clib.c3ai4cou44kc.ap-southeast-2.rds.amazonaws.com:5432/clib
    username: postgres
    password: mlt_dykim1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        # 외래키 제약조건을 비활성화
        javax.persistence.schema-generation.database.action: none
        javax.persistence.schema-generation.scripts.action: none
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        check_nullability: false
        # 외래키 제약조건 무시 설정
        dialect.constraints.foreign_key_check: false
  # Elasticsearch 설정 주석 처리 (ElasticSearch 서버가 없어서 연결 오류 발생)
  # data:
  #   elasticsearch:
  #     client:
  #       reactive:
  #         endpoints: localhost:9200
  #     repositories:
  #       enabled: true
  # Redis 설정 추가
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1시간 (밀리초 단위)
  redis:
    host: redis # 컨테이너 이름 (localhost에서 수정)
    port: 6379
    # 필요한 경우 아래 설정 추가
    # password:
    # timeout: 10000

server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework.data.elasticsearch.client.WIRE: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.clib: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    # Redis 로깅 추가
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:clib_secret_key_please_change_in_production}
    expiration: 86400000 # 24시간
